### ISSUE TITLE
TypeError: 'cardindex' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by julfla** [insanebits/spotify-connect-web#1]
Hi,

I'm very interested in what you've build to get spotify work on rpi.
I tried to install it and to run the container. Sadly, I get an error when running the container.

Here is what I have done, starting from a fresh rasbian jessie install on Rpi B+ (tried Rpi 2 also), install with apt.

```
pi@pi ~/spotify-connect-web $ docker --version
Docker version 1.3.3, build d344625

pi@pi ~/spotify-connect-web $ ls spotify_appkey.key 
spotify_appkey.key
pi@pi ~/spotify-connect-web $ ./run-with-docker .
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from connect import Connect
  File "/usr/src/app/connect.py", line 8, in <module>
    from console_callbacks import audio_arg_parser, mixer, error_callback, connection_callbacks, debug_callbacks, playback_callbacks, playback_setup
  File "/usr/src/app/console_callbacks.py", line 23, in <module>
    cardindex = int(args.device))
TypeError: 'cardindex' is an invalid keyword argument for this function
```

Build of the images contains the following error :

```
Get:109 http://ftp.us.debian.org/debian/ jessie/main python-wheel all 0.24.0-1 [47.5 kB]
Get:110 http://ftp.us.debian.org/debian/ jessie/main rename all 0.20-3 [12.4 kB]
Get:111 http://ftp.us.debian.org/debian/ jessie/main python-greenlet armel 0.4.2-2 [15.7 kB]
Get:112 http://ftp.us.debian.org/debian/ jessie/main python-gevent armel 1.0.1-2 [210 kB]
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/arm-linux-gnueabi/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/arm-linux-gnueabi/perl5/5.20 /usr/share/perl5 /usr/lib/arm-linux-gnueabi/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl .) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7, <> line 112.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
Fetched 64.4 MB in 3min 46s (285 kB/s)
Selecting previously unselected package libmagic1:armel.
(Reading database ... 10108 files and directories currently installed.)
Preparing to unpack .../libmagic1_1%3a5.22+15-2_armel.deb ...
```

Would you have run into the same error ?
Thank you very much for your intest,

**Comment by insanebits** [comment]
Hey, sorry for taking so long to answer :)

Which version did you used original(https://github.com/Fornoth/spotify-connect-web) or mine?

I don't see this error in Rpi2, it might be a problem if your alsa is older because according to the  docs
http://larsimmisch.github.io/pyalsaaudio/libalsaaudio.html#pcm-objects there should be attribute cardindex. 

The reason I've forked was to modify it in a way to be able to launch it without chroot or docker and run it as a service. But it will only work only on a rpi2 because of hardfloat vs softfloat.

**Comment by maumi** [comment]
hey julfla, you need to change text file requirements.txt to alsaaudio >= 0.8 and then build again with docker and run run-with-docker

**Comment by julfla** [comment]
Hi,

Thanks very much for tour replies.

Changing the alsaaudio version did the job.
I could run  it both on 2 and B+.

Have a nice day,
